language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest
notifications:
  webhooks: https://chat.citizenscience.ch/hooks/xnYY4LLB2LWXqmxHd/ABijvSTDjRoNvPLin6JyLTRyBDGNQTDmihLutzRcT5bDHmWg
