language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest
notifications:
  webhooks: https://chat.citizenscience.ch/hooks/HyKJmkFFsxjNTx2ce/RkjhJoNPEXLgnCbpKnkDL4iodkZhiCdRxGKaM8mu79mAcmRx
